# -*- coding: utf-8 -*-
"""200535426883_SALAH ABDULLAH KHALIL_off_C_BANK.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1FExaLhjIzUPFWznEduACdesxyBocZ5jW
"""

greeting = (input("Say a greeting ?")).strip().lower()

if greeting.startswith('hello') and greeting !="hello":
  print("0$")
elif greeting.startswith('h'):
   print("20$")
else:
   print("100$")